### ISSUE TITLE
Rename McLTT modules into McTT

### ISSUE THREAD

**Issue by Ailrun** [Beluga-lang/McTT#260]
Although the repo itself is renamed, there are some leftover "McLTT"s in this codebase.
They should be renamed.

**Comment by HuStmpHrrr** [comment]
also remember to change the hintdb to mctt as well.

**Comment by Ailrun** [comment]
#262 changed the `main` branch. Now we need to port the change into `ext/prop-eq` branch (which is probably even less complex, as infra-related changes are all done in that PR).

**Comment by HuStmpHrrr** [comment]
A merge will handle almost everything, no?

**Comment by HuStmpHrrr** [comment]
https://github.com/Beluga-lang/McTT/blob/2f662c95703ceb3766a2cc57a4a592ba4f349ec2/theories/Makefile#L46-L47

leftover

What is this? is it still needed?

**Comment by Ailrun** [comment]
@HuStmpHrrr Oh, yes. That's a helper target (which generates `_CoqProject` automatically). I will update that one as well.

**Comment by Ailrun** [comment]
> @HuStmpHrrr
> A merge will handle almost everything, no?

For example, `_CoqProject` added some modules, so we need to change them to use `Mctt`.
